apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: "{{ .Values.result.image }}:{{ .Values.result.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.result.service.port }}
