apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.port }}
    nodePort: {{ .Values.result.service.nodePort }}
  selector:
    app: result
