apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: "{{ .Values.worker.image }}:{{ .Values.worker.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
